### ISSUE TITLE
Include spy1985.csv

### ISSUE THREAD

**Issue by polanskya** [rkohli3/TSMOM#1]
Hello,

Thank you for amazing work.. I am relativley new to quant python and trying to learn following along your work.
You are missing some data files that are used in this program like spy 1985 csv.

Would you be so kind including all data files or instructions how to generate them?
Thabks

**Comment by rkohli3** [comment]
Will add some files. I think I might have removed those, for reasons I can't recall. I've started working on this module again. Just updated Plotly graphs in this module.

**Comment by polanskya** [comment]
Thanks..

Trying to run this again.. trying to get all references..

Stuck on this:

I assume , web.DataReader is statsmodels.tools.web', but apparently I am
wrong

AttributeError                            Traceback (most recent call
last)<ipython-input-8-0622a950ff13> in <module>----> 1
futures_exc_rets = get_excess_rets(daily_cum, kind = 'arth', freq =
'm', data_type= 'returns' )
~/fin_code/TSMOM/tsmom.py in get_excess_rets(data, freq, kind, shift,
data_type)    428                             start=
start_date)[0]['RF'])/100    429     elif freq == 'm':--> 430
rf = (web.DataReader("F-F_Research_Data_Factors",    431
               "famafrench",    432
start= start_date)[0]['RF'])/100
AttributeError: module 'statsmodels.tools.web' has no attribute 'DataReader'

**Comment by rkohli3** [comment]
It is not statsmodels. I had commented out pandas datareader. Should work now.
